### PR TITLE
add build for both amd64 and arm64

### PR DESCRIPTION
**Pull request by mrafsan-socotra**
Make separate file for situations we want to build for both platforms and tag them.

### CODE REVIEW

**Comment by mrafsan-socotra** [comment]
closing for now, to reopen in the new year

**Comment by mrafsan-socotra** [comment]
the default build is linux/amd64 is https://www.docker.com/blog/multi-platform-docker-builds/

**Comment by mrafsan-socotra** [comment]
This is specifically for keycloak-stack

**Comment by samuelfredrickson** [comment]
Is there a reason why this is a new file, instead of extending the existing docker-build-push workflow?

**Comment by mrafsan-socotra** [comment]
@samuelfredrickson just to make sure nothing is broken for other workflows. It seems like the arm64 builds are built differently for other repos and I wanted one that will be used directly by Keycloak-stack to begin with

**Review by samuelfredrickson — APPROVED** [review]

**Pull request merged**
